# CAS INVALIDE : Auto index
# ATTENDU : le parseur doit détecter que la valeur de auto index invalide et leur invalidite et rejeter
#           la config avec un message clair, sans crasher (exit(1)).

server
{
	listen					0.0.0.0:8080;
	server_name				webserv;
	client_max_body_size	10M;

	error_page 404			/errors/404.html;
	error_page 500			/errors/500.html;
	error_page 502			/errors/502.html;
	error_page 503			/errors/503.html;

	location /
	{
		allow_methods		GET;
		root				./www;
		index				index.html;
		autoindex			KCORP;
	}
}