# CAS INVALIDE : return mal formé
# La directive "return" n'a que le code HTTP, l'URL de redirection
# est manquante.
# ATTENDU : le parseur doit détecter l'argument manquant et rejeter
#           la config avec un message clair, sans crasher (exit(1)).

server
{
	listen					0.0.0.0:8080;
	server_name				webserv;
	client_max_body_size	10M;

	location /vieux
	{
		return				301;
	}
}