#DEFAULT CONFIGURE FILE FOR WEBSERV
#ON doit ajouter des location pour chaque page que notre site veux contenir

#USAGE :
# Ajouter une location si une famille d'URL doit avoir un comportement different que celui deja en place
# exemple : location / -> allow_methods = GET | location /upload (localhost:8080/upload) allow_methods = GET POST
# exemple 2 : location / root = ./www | location /downloads root = ./ fducrot/telechargement
# voir autre exemple dans docs/webserv-fichier-conf.md

server
{
	listen					0.0.0.0:8080;
	listen					0.0.0.0:7070;
	server_name				webserv;
	client_max_body_size	10M;

	error_page 404			/errors/404.html;
	error_page 500			/errors/500.html;
	error_page 502			/errors/502.html;
	error_page 503			/errors/503.html;

	location /
	{
		allow_methods		GET;
		root				./www;
		index				index.html;
	}
}

server
{
	listen			0.0.0.0:8080;
	server_name		webserv2;
}